### ISSUE TITLE
Fetch additional coin data

### ISSUE THREAD

**Issue by dcts** [dcts/radix.meme#127]
We not only need to fetch the metadata of a given token, but also additional data like:
```
vol24h?: number;
vol7d?: number;
change24h?: number;
change7d?: number;
lastPrice?: number;
bondingCurveProgress?: number;
availableSupply?: number;
maxSupply?: number;
```

Those are properties of `TokenState` ([reference](https://github.com/dcts/radix.meme/blob/1d726e0d6d052b316c09cdd159ad9369f7876858/app/_store/tokenSlice.ts#L7))

The fetching of the token happens here:
https://github.com/dcts/radix.meme/blob/1d726e0d6d052b316c09cdd159ad9369f7876858/app/_store/tokenSlice.ts#L89

I suggest to adapt the return type of the asyncThunk from `TokenInfo` to `TTokenData` and adapt the extra reducer accordingly.

**Comment by fliebenberg** [comment]
The variables other than vol... and change... are already available. To calculate the volume and change vars, we will have to load the list of txs for the token.
I will work on this first this week.
