### ISSUE TITLE
Add component_address to metadata of the resource

### ISSUE THREAD

**Issue by dcts** [dcts/radix.meme#153]
To be able to fetch all relevant data without the need of a lookup store, we should store the component address of the token curve component that created the token inside the metadata of the resource. 

For instance, we have this token:
https://www.radix.meme/token/resource_tdx_2_1t47g87wjahnypzu9kmwhhzurt4qsfc288rvkeavhuh7sj7ygevrpwj?componentAddress=component_tdx_2_1cppce9u6q3eypy8wrw950hqk6gm8awhvhgx356mtlxje9ejx6ch3fa

**resource**: resource_tdx_2_1t47g87wjahnypzu9kmwhhzurt4qsfc288rvkeavhuh7sj7ygevrpwj
**component**: component_tdx_2_1cppce9u6q3eypy8wrw950hqk6gm8awhvhgx356mtlxje9ejx6ch3fa

We should store the component address in the metadata of the resource so that is appears here:
https://stokenet-dashboard.radixdlt.com/resource/resource_tdx_2_1t47g87wjahnypzu9kmwhhzurt4qsfc288rvkeavhuh7sj7ygevrpwj/metadata

This should be automatically done in the scrypto code without the user having to do anything.

**Comment by fliebenberg** [comment]
Implemented. Component address now stored in metadata field: "radix_meme_component".
