### ISSUE TITLE
How to show progress?

### ISSUE THREAD

**Issue by dcts** [dcts/radix.meme#161]
To show the progress on the bonding curve we have different strategies:
1. show the % of tokens sold (a bit misleading, as the first 10k XRD will already account for 20% supply minted)
2. show the number of XRD net inflows into the coin (now my 10k XRD will only be 10/333 = 3% of total inflows)

In case we decide for scenario 2, we should expose the current vault holdings to the `getTokenData` function.

**Comment by fliebenberg** [comment]
I also think showing the progress with in terms of XRD is more reflective of the "real" progress.

**Comment by maurojose** [comment]
The second

**Comment by dcts** [comment]
@fliebenberg how would we get that data? Simply fetch the number of XRD inside the BondingCurve vault? 

Can you fetch this data and expose it as part of `getTokenData` function?

**Comment by fliebenberg** [comment]
Did a quick PR before work this morning.
