### ISSUE TITLE
Buy / Sell flow feedback

### ISSUE THREAD

**Issue by maurojose** [dcts/radix.meme#170]
When I tried to buy, I did not know if the amount was XRD amount or token amount!
Just add a "XRD" IN THE RIGHT SIDE OF INPUT FIELD

![Screenshot_20241001_164854_Brave.jpg](https://github.com/user-attachments/assets/28adb75d-861a-4f64-858d-aad10230456a)

**Comment by maurojose** [comment]
And if possible, show how many tokens will be bought

**Comment by maurojose** [comment]
And the final price

**Comment by maurojose** [comment]
And the final price.

**Comment by dcts** [comment]
On it!

**Comment by fliebenberg** [comment]
@dcts are you able to calculate the amount of tokens you will receive? I can add  a couple of functions to calc those if you need.
