### ISSUE TITLE
Token Jpg

### ISSUE THREAD

**Issue by maurojose** [dcts/radix.meme#171]
![Screenshot_20241001_165113_Brave.jpg](https://github.com/user-attachments/assets/1638d308-fcd1-46b0-a3eb-0612310d26f3)

The image is very small compared to the container, and there is nothing showing that the image should be jpeg, jpg, or png before adding the image

**Comment by saidam90** [comment]
PR #193

**Comment by dcts** [comment]
Closing, even though the PR is not merged, it solves all those issues mentioned here :)
