### ISSUE TITLE
Discuss using metadata standard for social links

### ISSUE THREAD

**Issue by dcts** [dcts/radix.meme#195]
@fliebenberg what do you think if we use metadata standard followed by selfie social and defiplaza:
https://selfi-social.gitbook.io/selfi-social-standards

<img width="542" alt="Bildschirmfoto 2024-10-05 um 02 45 41" src="https://github.com/user-attachments/assets/436fe8a2-26a1-4ffd-8fc1-8fb47a899baf">
<img width="343" alt="Bildschirmfoto 2024-10-05 um 02 45 46" src="https://github.com/user-attachments/assets/25c8846f-8ed7-4dd6-a9ff-18bac08d3f61">
<img width="541" alt="Bildschirmfoto 2024-10-05 um 02 45 57" src="https://github.com/user-attachments/assets/b24e2755-edf3-41ee-9cc2-332e74fb71a1">

**Comment by fliebenberg** [comment]
Have connected with beem to make sure I understand how to set it up correctly.
My only concern with their approach is that it is another layer in the metadata, so does not display as nicely as when each field is at the "top" layer. 
Also it might be a bit harder for frontends to know which social icons to display from just a url, while ours specify the social platform in the name.

**Comment by dcts** [comment]
Yes I think theres pro's and con's. I do agree on the formatting and also think it removes information (the key or description for each value). But upsides are that we might get a lot of value for free when using standards, but not sure what specifically those are.

**Comment by fliebenberg** [comment]
I suggest for now we go with the standard. We can still lookup which service an address relates to from the domain name. I will implement in the next version of the component I will release later today.

**Comment by fliebenberg** [comment]
OK, If we implement their standard we have to make sure the user puts in a valid URL otherwise the tx will fail in the component, which now saves the links as Urls. So something to consider when designing the frontend.

**Comment by fliebenberg** [comment]
I have implemented their standard and out tokens now have "social_urls" metadata field that contains an array of urls.
