### ISSUE TITLE
Add "how it works" modal

### ISSUE THREAD

**Issue by dcts** [dcts/radix.meme#34]
I suggest to add a secondary button on the landing page "How it works". 

That could then open a modal, I suggest using this:
https://ui.aceternity.com/components/animated-modal

## Inspiration from Competitors:

**SunPump.meme**
<img width="1029" alt="Bildschirmfoto 2024-09-22 um 21 33 57" src="https://github.com/user-attachments/assets/7f334d78-a3fd-42c1-84cf-964879a47449">

**Pump.fun**
<img width="449" alt="Bildschirmfoto 2024-09-22 um 21 34 57" src="https://github.com/user-attachments/assets/afff54d6-dc5d-47aa-b70b-6cd8a6a0304e">

## Content

radix.meme prevents rugs by making sure that all created tokens are safe. Each coin on radix.meme is a fair-launch with no presale and no team allocation.
1. pick a coin that you like (or launch your own!)
2. buy the coin on the bonding curve
3. sell at any time to lock in your profits or losses
4. when enough people buy on the bonding curve it reaches a market cap of $69k
5. $12k of liquidity is then deposited in ociswap to enable further trading.

@maurojose could you provide design for the modal?

**Comment by SiegfriedBz** [comment]
to implement fast and nice I would suggest

https://ui.aceternity.com/components/animated-modal
or
https://ui.shadcn.com/docs/components/dialog

**Comment by dcts** [comment]
implemented
