### ISSUE TITLE
Questions for backend<->frontend connection

### ISSUE THREAD

**Issue by dcts** [dcts/radix.meme#36]
# All user journeys

Please check whether this mapping of user journey to scrypto function/method calls is correct:
- create new token -> call `TokenCurves.new_token_curve_simple` function
- buy existing token -> call `buy` method of the `TokenCurve` component/instance and specify the amount of XRD to spend
- sell existing token -> call `sell` method of the `TokenCurve` component/instance and specify amount of MEME tokens to sell

# Questions

1. I want to store all memecoins created in a redux state. Can you provide the radixGatewayAPI endpoint and arguments I need to pass to get this information? ("get all component addresses created from this blueprint")

2. How can I fetch metadata about a given memecoin (if I have the address of the component)? Should that be done with gatewayAPI as well? 

3. Do you have the contract deployed on stokent? For connecting the data it would be great if you could provide:
- app address (connect button has to specify which app to connect to)
- address of TokenCurves component (for fetching all memecoins created)
- address of 1 or 2 example memecoins generated

4. How will we get metadata about a memecoin? More specifically: Can we get:
- 24h vol / price change
- 7d vol / price change
- all trades?
- how do we get chart data?
Will we have to fetch all trades from the ledger and compute it on the go? Can we even do that without caching the data in a centralized DB and using a cronjob every 5 mins to update?

5. Will each trade generate an NFT or is that only needed in dexter because of limit orders?

6. Are we allowing same tokenName + symbol?

7. In the scrypto code I saw all things are updatable, name, symbol etc. Should we at least keep the name and symbol immutable after creation? 

8. Is the symbol case sensitive (e.g. are they always uppercased or is it possible To have "DeXtEr" as symbol)?

**Comment by fliebenberg** [comment]
> * buy existing token -> call `buy` method of the `TokenCurve` component/instance and specify the amount of XRD to spend

To buy tokens there are 2 options:
1. Call the "buy" method and send a bucket with XRD. The function will return tokens to the value of the XRD in the bucket.
2. Call the "buy_amount" method where the user specifies the amount of tokens and sends a bucket with XRD. The function returns the amount of tokens specified and any excess XRD left over.

**Comment by fliebenberg** [comment]
> * sell existing token -> call `sell` method of the `TokenCurve` component/instance and specify amount of MEME tokens to sell

Similar to the buy options there are 2 sell options:
1. Call the "sell" method and send a bucket of tokens. The method returns the appropriate amount of XRD.
2. Call the "sell_for_xrd_amount) method where the user specifies the amount of XRD they want to receive and sends a bucket of tokens. The method returns the required amount of XRD and any tokens left over.

**Comment by fliebenberg** [comment]
> 2\. How can I fetch metadata about a given memecoin (if I have the address of the component)? Should that be done with gatewayAPI as well?

You can get the details of each coin just like you would for any other token on Radix. The /state/entity/details endpoint should provide all the info about the token. Most of what you would want would be in the metadata portion of the data.

**Comment by fliebenberg** [comment]
> 3\. Do you have the contract deployed on stokent? For connecting the data it would be great if you could provide:

Will send this info as soon as I have a version deployed on stokenet. Will see if I can do it from work today.

**Comment by fliebenberg** [comment]
> 7\. How will we get metadata about a memecoin? More specifically: Can we get:
> 
> * 24h vol / price change
> * 7d vol / price change
> * all trades?
> * how do we get chart data?
>   Will we have to fetch all trades from the ledger and compute it on the go? Can we even do that without caching the data in a centralized DB and using a cronjob every 5 mins to update?

This data we will need to fetch either from transactions or from events. I have not added events to the component yet, but plan to do that tonight.
Essentially we will have to fetch all transactions/events for a specific coin and then calculate whatever stats we need from the fetched data. The api only returns the most recent 100 txs/events at a time, so you might need to do several calls to get more historical data. However, you will only need to do this once when the token is loaded and thereafter you can just periodically load the latest ones to check if there has been an update since you last loaded. In general this is still quite quick though and we can render the whole page first and then lazy load the historic data.
You do not need to cache the data in a separate database.

**Comment by fliebenberg** [comment]
> 5\. Will each trade generate an NFT or is that only needed in dexter because of limit orders?

No. Not needed in this case.

**Comment by fliebenberg** [comment]
> 6\. Are we allowing same tokenName + symbol?

There is no way to prevent this really. We are not even tracking the name/symbol of the tokens really. We just create them initially, but then allow the owner of the token to change the metadata at any time. SO they can change the token name/symbol/decsription at any point, just like on a normal Radix token.

**Comment by fliebenberg** [comment]
> 7. In the scrypto code I saw all things are updatable, name, symbol etc. Should we at least keep the name and symbol immutable after creation?
> 8. Is the symbol case sensitive (e.g. are they always uppercased or is it possible To have "DeXtEr" as symbol)?

7. I want these tokens to be the same as any other token on Radix and also not burden us with being responsible for the admin of tokens. So I prefer to just give the owner of the token the right to change the name/symbol/description whenever they wish. We will just display whatever is the current values.
8. On Radix a token symbol is just a metadata field and there are no strict enforcement of a standard. They do provide some guidance in terms of how it will be displayed in the docs, but this is not enforced. We could decide on enforcing some standard (e.g. max number of characters), but I think we should allow capitals and small letters. It is just another level of creativity the token creator can use. Of course, whatever we enforce initially could still be changed by the owner afterwards.
