### ISSUE TITLE
Make Navbar Responsive

### ISSUE THREAD

**Issue by dcts** [dcts/radix.meme#54]
Add responsive design of the navbar , e.g. create hamburger menu on moble. 

I suggest to copy the functionality and animations from the DeXter Navbar:
https://github.com/DeXter-on-Radix/website/blob/main/src/app/components/NavBar.tsx

**Comment by SiegfriedBz** [comment]
@dcts this is done, right ?

**Comment by dcts** [comment]
Yes I just realized we dont need a hamburger menu at all..!
