### ISSUE TITLE
buttons

### ISSUE THREAD

**Issue by maurojose** [dcts/radix.meme#77]
![image](https://github.com/user-attachments/assets/e939f9cf-9abd-4371-a1c3-40dbb8086d52)

buttons reference: https://www.figma.com/proto/fO9rrn6yZlRQvclVkHz8T9/radix.meme?node-id=191-102&node-type=frame&t=u4hMr2BwXu8GXD6W-1&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=84%3A60

CTA big (desktop):
- fill: #A7D22D
- stroke: #637E17 1px
- bottom stroke when default: #637E17 4px
- radius: 8px
- font: 16px
- icon: 16px
- padding X: 16px
- padding y: 8px
- height: 44px
- shadow: #CBEF63 40%, offset y: 4px, spread: 2, blur: 40px

CTA small (mobile):
- fill: #A7D22D
- stroke: #637E17 1px
- bottom stroke when default: #637E17 4px
- radius: 8px
- font: 14px
- icon: 14px
- padding X: 16px
- padding y: 8px
- height: 36px
- shadow: #CBEF63 40%, offset y: 4px, spread: 2, blur: 40px

primary big:
- fill: #A7D22D
- stroke: #637E17 1px
- bottom stroke when default: #637E17 4px
- radius: 8px
- font: 16px
- icon: 16px
- padding X: 16px
- padding y: 8px
- height: 44px
- shadow: no shadow

primary small (mobile):
- fill: #A7D22D
- stroke: #637E17 1px
- bottom stroke when default: #637E17 4px
- radius: 8px
- font: 14px
- icon: 14px
- padding X: 16px
- padding y: 8px
- height: 36px
- shadow: no shadow

secondary big:
- fill: #141414
- stroke: #fff 1px
- bottom stroke when default: #fff 4px
- radius: 8px
- font: 16px
- icon: 16px
- padding X: 16px
- padding y: 8px
- height: 44px
- shadow: no shadow

secondary small (mobile):
- fill: #141414
- stroke: #fff 1px
- bottom stroke when default: #fff 4px
- radius: 8px
- font: 14px
- icon: 14px
- padding X: 16px
- padding y: 8px
- height: 36px
- shadow: no shadow

**Comment by dcts** [comment]
Please whoever implements this do not worry about implementing all responsiveness, only implement 1 version of the button and use for both mobile and desktop.

**Comment by SiegfriedBz** [comment]
@maurojose please specify hover effects

draft PR #123 

[Untitled_ Sep 26,2024 3_38 PM (1).webm](https://github.com/user-attachments/assets/dff0e509-fdf7-4fa2-9784-d08949fa88a9)

**Comment by dcts** [comment]
@SiegfriedBz If you create those buttons, can you make them standalone UI "client" components, such that we can reuse them? Ideally I think of something like this:

```ts
iterface RadixMemeButton {
  buttonStyle: ButtonStyle;
  additionalClasses: string;
  icon: string;  // could be an SVL html element as well
  text: string;  // text of the button, e.g. "Launch your token"
  onclick?: () => {};  // onclick handler
  redirectUrl?: string;
  redirectTargetBlank?: boolean; // if TRUE, redirects to the redirectUrl using a new tab
}

enum ButtonStyle {
  PRIMARY = "PRIMARY,
  SECONDARY = "SECONDARY",
}
```

**Comment by SiegfriedBz** [comment]
@dcts I created PR https://github.com/dcts/radix.meme/pull/168 in the "spirit" of reusability you mentioned (same component for buttons, links and spans)

@maurojose I used your specs and added active and hover states
